### ISSUE TITLE
Criar o modelo de dados para Usuário

### ISSUE THREAD

**Issue by gitrodrigues1** [gitrodrigues1/HackathonEcommerce#4]
Sugestões de campos:

name: String
email: String
address: Address
password: String
createdAt: LocalDateTime
updatedAt: LocalDateTime

**Comment by NevesHenry** [comment]
Commit: https://github.com/gitrodrigues1/HackathonEcommerce/commit/60161344b2f20d081f2fabe7460fafa955258307
